### ISSUE TITLE
[8][TBAPI-0KA] Implement popup hint message for Icons all around the UI

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#1447]
With the last update to the icon class we now have support to add hints, which would be really helpful to explain rookie what buttons do, see #1413 

```
some_hint_message = "Can be some text or"
some_hint_message = "some.translation.key" // that gets translated within the class
<Icon title={some_hint_message}/>
```

Shame to say but I also didn't know what the pin does
![image](https://user-images.githubusercontent.com/33128181/39034811-0ec4c0d4-4478-11e8-8177-6eb7a4ebc875.png)

Task for this issue:
- [ ] find all icons that need a hint (should be all icons actually)
- [ ] add proper explanatory message

**Comment by gibbsfromncis** [comment]
I'll take this one

**Comment by gibbsfromncis** [comment]
I've no time so reassigning this one to my friend @TBAPI-0KA

**Comment by wmbutler** [comment]
I'm not sure which languages you speak, but I'd suggest you set them all with the appropriate english language and allow others to fill in the gaps at their leisure. Tell me what your hours should be set to in order to justify your time.

**Comment by TBAPI-0KA** [comment]
English and Russian, from our localizations, but it doesn't matter. To set appropriate titles, I need to find them on UI, fill in those that I understand what they do, and ask for the rest. If you think that it worth to do, I'm more than happy to do that and report time then.

**Comment by sschiessl-bcp** [comment]
I wasn't aware it's that many, but good job! I would suggest for now fill in the prominent ones that you do understand and the rest is on the fly

**Comment by happyconcepts** [comment]
Help me understand why this is needed?

**Comment by sschiessl-bcp** [comment]
I don't understand your question. What is this?

**Comment by happyconcepts** [comment]
Just because we can make hints, doesn't mean we should. Updating any of them in the future is a translation headache. So why is this needed please? Do you understand now?

**Comment by sschiessl-bcp** [comment]
That would have been something to discuss before the work starts :)

Anyways, I said in my initial post that 
 -  find all icons that need a hint (should be all icons actually)
The sentence in the brackets was just my personal wish, of course common sense is needed when an icon itself is self-explanatory.

Translation headache we have anyways in such a big project.

To answer your question directly: It is needed anywhere, where it is not extremely obvious what the icon does

**Comment by wmbutler** [comment]
I agree with the intent of this issue. Hints are a pretty standard part of modern design and are helpful especially for new users to the platform.

**Comment by happyconcepts** [comment]
>That would have been something to discuss before the work starts :)

Indeed, this one seems a great way to waste development funds and should have been de-prioritized earlier in my opinion. If high priority bugs were fixed... and if the key features like sending bts and charts were working ... then I would acquiesce and lighten up here.

So if you are still wondering... @sschiessl-bcp what I still do not understand is:

>That would have been something to discuss before the work starts :)

Why are important bugs like #1397 Order Expiration Date bug left to languish...bugs are an obvious detriment to all users and not just for the new ones. #1397 is even tagged as a bug, with high priority.

Today we are well past the 0501 sprint yet this bug exists since the favor of @sschiessl-bcp and @wmbutler is to discuss the text hints in *this* issue.

Moreover, surprising that a passing comment here in this issue gets such prompt response by @wmbutler and @sschiessl-bcp while I am summarily ignored on #1469 which is an Order Expiration Date bug in the order entry screen...but that would explain the snarky comment by @sschiessl-bcp:

>That would have been something to discuss before the work starts :)

Yes it appears problematic here, the communication.

**Comment by sschiessl-bcp** [comment]
I only react on email notification which I get for my reported issues, or where I already have commented. That's why I didn't see the other one. I am not often browsing the issues page and look what is interesting, I leave that to Mr. Butler.

I don't think anyone prioritized this issue. Issues are still self assigned, though I agree that there should be force assigning (or in lack thereof denying funding for other tasks) of important issues and streamlinig the workforce.

Your work is appreciated, I didn't mean to undervalue your contribution. Please don't hesitate to demand explanation for important issue that get lost for whatever reason.

**Comment by wmbutler** [comment]
@happyconcepts stop being such a dick. Issues "languish" until someone claims them. This is an open source project and neither I nor you can force anyone to work on something that doesn't interest them. All I have the ability to do is to make bugs more interesting to fix by increasing the bounty on them. If there is an issue you think is important, suggest a bounty increase to resolve it.

This isn't a situation where there is a trade off. If you think a problem needs to be fixed, quit bitching and fix it. If you think a bounty is low for an item, state it on that issue, not on some other random issue that doesn't interest you.

**Comment by happyconcepts** [comment]
> @happyconcepts stop being such a dick. Issues "languish" until someone claims them. This is an open source project and neither I nor you can force anyone to work on something that doesn't interest them.

I am here with interest, to contribute, and I describe how difficult it is to do so...and this is your response @wmbutler as the project manager .. to openly call me a dick for trying to contribute ... instead of doing anything responsive or professional or courteous about a bug #1469 for example.

The unfortunate reality is that real Bitshares bug issues "languish" either because you ignore them or because you enjoy getting paid to fix your own bugs, but from your sissy tone and namecalling @wmbutler I am getting the feeling I will not be able to do anything to get you to start to value any of my contributions.

If the Bitshares worker proposal is now paying you thousands of dollars per month to call me a dick I suppose I should change my vote or stop contributing or both? Is that your message to me?

**Comment by wmbutler** [comment]
No, the WP is not paying me to call you a dick. That's just my personal opinion.

**Comment by sschiessl-bcp** [comment]
@wmbutler
The namecalling is unnecessary, please keep it professional

Without taking sides here I think it would be a shame to lose a contributor. We all want to push in the same direction. We are all different characters and need to learn to play alongside, honest and open communication is key.

Anyways, @happyconcepts would you be willing to finish this issue?

**Comment by happyconcepts** [comment]
@sschiessl-bcp @wmbutler Thank you for your communicative efforts and sensibility. I am working some bugfixes and the market fee issue so I am not able to help with this one #1447.

Yes let's please do our best to work together for the good of the bitshares chain amid the increasing competition.

**Comment by TBAPI-0KA** [comment]
While I agree that this issue isn't the most important, as I stated earlier, and isn't complicated, it's still required certain tidiness and was significantly time-consuming. My qualification allows me to work on tasks of almost any complexity, but I'm pretty new here on the project, so I'm just taking the issues which are clear to me and aren't assigned to somebody else. BTW, this particular one forced me to visit a lot of pages that I couldn't even imagine they exist, which gave me a much better understanding of the project. And at the end, somebody should do the boring job as well, right? So let's do what we can do, and deliver a great product together, shall we?

Back to the deal. The issue is complete, PR sent. The following things were performed:

- icons were found on UI and screenshoted where possible. Sometimes this required to change code temporarily because some icons are shown only under specific conditions (i.e. positive balance of particular asset). I'm not publishing these screenshots, but if somebody stuck finding some icon - ask me, most likely, I know where it is, and can even provide a screenshot :) In the worst case, if I couldn't find icon on UI, I examined the code to understand what particular icon does, and wrote good title for it;
- added contextual messages for all icons. By "contextual" I mean different usages of the same physical icon file. Such situations are handled correctly, and titles can be changed independently;
- removed unused icons. I have feeling that some more aren't used anymore, but they are bound to different pieces of code. This code looks outdated, but I didn't take responsibility to remove it - there might be implicit dependencies;
- full English and manual Russian translation;
- boilerplate for the rest of the translations;
- used the same naming convention for icon titles all around the project;
- fixed few small bugs, like duplicated title attribute;
- added titles for new icons after Market Ticker functionality was merged.

I spent 4 hours of pure working time earlier, and 8h 50m now. I understand that almost 13 hours might be too much for such kind of issue, so I hope you'll fairly adjust estimation, using commits review and UI changes as a reference.

**Comment by TBAPI-0KA** [comment]
I'm good with 8.

**Comment by TBAPI-0KA** [comment]
@svk please close this issue as PR #1513 was reviewed and merged successfully.

**Comment by gibbsfromncis** [comment]
@svk31 I'm closing this issue by @TBAPI-0KA request to help him able to receive bounties for this issue
